Update wiki_to_pdf.yml

diff --git a/.github/workflows/wiki_to_pdf.yml b/.github/workflows/wiki_to_pdf.yml
--- a/.github/workflows/wiki_to_pdf.yml
+++ b/.github/workflows/wiki_to_pdf.yml
@@ -108,13 +108,13 @@ jobs:
 
       - name: Generate PDFs
         run: |
-          set -euo pipefail
+          # set -euo pipefail
           
           export LANG=C.UTF-8
           export LC_ALL=C.UTF-8
           
           if [ ! -d "$GITHUB_WORKSPACE/assets" ]; then
-            echo "ERROR: $GITHUB_WORKSPACE/assets not found. (메인 레포에 assets 폴더가 없거나 checkout 경로가 다름)"
+            echo "ERROR: $GITHUB_WORKSPACE/assets not found."
             exit 1
           fi
           
